machine:
  pre:
   - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
   - sudo pip install docker-compose
  services:
    - docker

dependencies:
  override:
    - docker info
    - >
      if [ -n "${RUN_NIGHTLY_BUILD}" ]; then
        echo "running base img build..." && docker build --rm=false -t gr4per/nginx-rp:base -f Dockerfile.base .
      fi
    - docker build --rm=false -t gr4per/nginx-rp:latest .

test:
  override:
    - docker-compose up -d
    - sleep 10
    - curl --retry 10 --retry-delay 1 localhost:8080/public/health_check.html

deployment:
  development:
    branch: develop
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
      - docker tag gr4per/nginx-rp:latest gr4per/nginx-rp:dev
      - docker push gr4per/nginx-rp:dev
  production:
    branch: master
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
      - >
        if [ -n "${RUN_NIGHTLY_BUILD}" ]; then
          echo "running base img deploy..." && docker push gr4per/nginx-rp:base
        fi
      - docker push gr4per/nginx-rp:latest
