version: '2'
services:
  main:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - registrator
    environment:
      USER_IDENTITY: '{\"id\":\"test123\", \"username\": \"testUser1\"}'

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    #restart: always
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ['-ip=${HOST_IP}', 'consul://localhost:8500']

  consul:
    command: -bootstrap-expect=1 -ui
    image: gliderlabs/consul-server
    labels:
      - 'SERVICE_NAME=consul'
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
