version: '2'
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "-server -bootstrap -ui-dir /ui"
  registrator:
    image: "gliderlabs/registrator:latest"
    container_name: "registrator"
    depends_on:
      - consul
    command: "consul://consul:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  nginx:
    #network_mode: host
    build:
      context: .
    network_mode: host
    volumes:
      - .:/module
    ports:
      - "8080:8080"
    extra_hosts:
      - "consul:$HOST_IP"
    depends_on:
      - registrator
