version: '2'
services:
  main:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - registrator

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    #restart: always
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ['-ip=${HOST_IP}', 'consul://localhost:8500']

  consul:
    command: "-server -bootstrap -ui-dir /ui"
    image: "progrium/consul:latest"
    container_name: "consul1"
    labels:
      - 'SERVICE_NAME=consul'
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
