version: '2'
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul1"
    network_mode: "host"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "-server -bootstrap -ui-dir /ui"
  registrator:
    image: "gliderlabs/registrator:latest"
    container_name: "registrator"
    network_mode: "host"
    depends_on:
      - consul
    command: "consul://localhost:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  nginx:
    build:
      context: .
    volumes:
      - .:/module
    extra_hosts:
      - consul:172.17.0.1
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - registrator
